import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <article className="prose mx-auto max-w-3xl px-4 py-16">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: March 2026</p>

      <h2>1. Service Description</h2>
      <p>
        ScopePro is an AI-powered tool that generates scopes of work for
        painting contractors. You upload photos and job details, and the service
        generates a structured scope document using artificial intelligence.
      </p>

      <h2>2. Account Registration</h2>
      <p>
        You must create an account to use ScopePro. You are responsible for
        maintaining the security of your account credentials. You must provide
        accurate information when creating your account.
      </p>

      <h2>3. Credits and Payments</h2>
      <p>
        ScopePro operates on a credit-based system. Each scope generation
        consumes one credit. New accounts receive 3 free credits. Additional
        credits can be purchased in packs (10, 25, or 50) via Stripe. All
        prices are in Australian Dollars (AUD) and include GST. Credits do not
        expire. Refunds are issued only when AI generation fails — failed
        generations automatically refund the credit used.
      </p>

      <h2>4. AI-Generated Content</h2>
      <p>
        Scopes generated by ScopePro are produced by artificial intelligence and
        should be reviewed by a qualified professional before use. ScopePro does
        not guarantee the accuracy, completeness, or suitability of generated
        scopes. You are responsible for verifying all scope items before
        presenting them to clients.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Upload content that is illegal, harmful, or violates third-party rights</li>
        <li>Attempt to manipulate the AI system through prompt injection</li>
        <li>Use the service for any purpose other than generating painting scopes of work</li>
        <li>Share your account credentials with others</li>
        <li>Reverse-engineer or attempt to extract the AI models or prompts</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        You retain ownership of the photos you upload and the descriptions you
        provide. The generated scope content is licensed to you for commercial
        use. ScopePro retains ownership of the service, software, and AI
        systems.
      </p>

      <h2>7. Data and Privacy</h2>
      <p>
        Your use of ScopePro is also governed by our{" "}
        <a href="/privacy">Privacy Policy</a>. By using the service, you
        consent to the processing of your data as described therein.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        ScopePro is provided &quot;as is&quot; without warranty of any kind. To
        the maximum extent permitted by Australian law, ScopePro shall not be
        liable for any indirect, incidental, or consequential damages arising
        from your use of the service. Our total liability shall not exceed the
        amount you have paid for credits in the preceding 12 months.
      </p>

      <h2>9. Account Termination</h2>
      <p>
        You may delete your account at any time. We may suspend or terminate
        accounts that violate these terms. On account deletion, all data is
        permanently removed.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These terms are governed by the laws of New South Wales, Australia. Any
        disputes shall be resolved in the courts of New South Wales.
      </p>

      <h2>Contact</h2>
      <p>
        For questions about these terms, email{" "}
        <a href="mailto:hello@scopepro.com.au">hello@scopepro.com.au</a>.
      </p>
    </article>
  );
}
